type: object
properties:
  type:
    type: string
    example: settings
  id:
    type: string
    description: ID of setting.
    example: communication:email-3JD1mkXfz
  attributes:
    type: object
    properties:
      type:
        type: string
        description: Description of type of setting
        example: communication
      manual:
        type: boolean
        description: (Only used if communication channel is set to `sns`). True for allowing users to manually send individual checks, false for disabling this option.
        example: false
      enabled:
        type: boolean
        description: True for turning on channel
        example: true
      filter:
        type: object
        properties:
          riskLevels:
            $ref: ../fields/risk-level.yml
          statuses:
            type: array
            description: "(Only used if communication channel is set to `sns`). An array of check outcomes to be notified about."
            items:
              type: string
              enum:
                - "SUCCESS"
                - "FAILURE"
          services:
            $ref: ../types/services.yml
      configuration:
        type: object
        properties:
          channelName:
            type: string
            description: Label to display in the application (to distinguish between multiple instances of the same channel type).
            example: someChannelName
          users:
            type: array
            description: If communication channel is set to "email", then "users" is an array of users with at least `readOnly` access to the account. If communication channel is set to "sms", then "users" is an array of users with verified mobile numbers that have at least `readOnly` access to the account.
          url:
            type: string
            description: (Only used if communication channel is set to `slack` or `ms-teams`). Url to webhook
            example: "https://hooks.slack.com/services/your-slack-webhook"
          channel:
            type: string
            description: (Only used if communication channel is set to `slack` or `ms-teams`). Name of channel
            example: "#your-channel"
          displayIntroducedBy:
            type: boolean
            description: (Only used if communication channel is set to `slack` or `ms-teams`). True for adding user to message.
          displayResource:
            type: boolean
            description: (Only used if communication channel is set to `slack` or `ms-teams`). True for adding resource to message.
          displayTags:
            type: boolean
            description: (Only used if communication channel is set to `slack` or `ms-teams`). True for adding associated tags to message.
          displayExtraData:
            type: boolean
            description: (Only used if communication channel is set to `ms-teams`).
          serviceName:
            type: string
            description: (Only used if communication channel is set to `pager-duty`). Your service name.
            example: "yourServiceName"
          serviceKey:
            type: string
            description: (Only used if communication channel is set to `pager-duty`). Your service key.
            example: "yourServiceKey"
          arn:
            type: string
            description: (Only used if communication channel is set to `sns`). ARN of SNS
            example: |
              { "arn": "arn:aws:sns:REGION:ACCOUNT_ID:TOPIC_NAME"}
      created-by:
        type: string
        description: ID of user that created this communication setting
        example: n6yTeW_lx
      created-date:
        type: string
        description: Epoch string for the date time when the communication setting was created
        example: 1565165403747
      channel:
        $ref: ../fields/communication-channels.yml
      is-account-level:
        type: boolean
        description: Defines if communication setting is set at an account level
        example: false
      is-group-level:
        type: boolean
        description: Defines if communication setting is set for a group
        example: false
      is-organisation-level:
        type: boolean
        description: Defines if communication setting is set at an organisation level
        example: true
  relationships:
    type: object
    properties:
      account:
        type: object
        properties:
          data:
            type: object
            description: <code>null</code> if only creating organization-level setting.
            properties:
              type:
                type: string
                example: accounts
              id:
                type: string
                description: Cloud Conformity account ID
      organisation:
        type: object
        properties:
          data:
            type: object
            description: Information about organisation.
            properties:
              type:
                type: string
                example: organisations
              id:
                type: string
                description: Cloud Conformity organisation ID
