type: object
properties:
  type:
    type: string
    example: accounts
  id:
    type: string
    description: ID of the account.
    example: H19NxMi5-
  attributes:
    type: object
    properties:
      accountId:
        type: string
        description: ID of the account.
        example: HksLj2_
      configuration:
        type: object
        properties:
          title:
            type: string
            description: This attribute is report title, which must be a string
            example: Daily report of IAM
          sendEmail:
            type: boolean
            description: This attribute is optional. When report was scheduled, aka the attribute scheduled is true, this is a toggle to send report to specific email addresses. It should be boolean when provided
            default: false
          emails:
            type: array
            description: This attribute is optional, represents email addresses that report would be sent to. It must be a array contains valid email addresses.
            items:
              type: string
          filter:
            $ref: ./filter.yml
          scheduled:
            type: boolean
            description: This attribute is optional, means whether the report is scheduled. It must be a boolean value when it was provided.
            default: false
          frequency:
            type: string
            description: This attribute is optional, but when the attribute scheduled is true, it must be a cron expression string that starts with day of month field. For example, daily cron expression would be * * *
            example: "* * *"
          tz:
            type: string
            description: This attribute is optional. It's used as which timezone the report schedule is based on, when the attribute scheduled is true.
            example: Australia/Sydney
          generateReportType:
            $ref: ../../shared-schemas/fields/generated-report-type.yml
          includeChecks:
            type: boolean
            description: Specifies whether or not to include individual checks in PDF reports when total number of checks is below 10000.
            default: false
          shouldEmailIncludePdf:
            type: boolean
            description: This attribute is optional. Specifies whether or not to include PDF attachment in email.
            default: true
          shouldEmailIncludeCsv:
            type: boolean
            description: This attribute is optional. Specifies whether or not to include CSV attachment in email.
            default: true
  relationships:
    type: object
    properties:
      organisation:
        $ref: ./organisation-short.yml
      account:
        $ref: ./account-short.yml
      group:
        type: object
